### PR TITLE
Added trailing HTTPHeaders for custom error reporting

### PR DESCRIPTION
**Pull request by fabianfett**
Issue: #636

### CODE REVIEW

**Comment by MrMage** [comment]
I think this would be a breaking change; @fabianfett do you think we could get this in before 1.0?

The overall intention of the PR makes sense to me; I wonder whether we could find a more elegant way than returning a tuple, though. @glbrntt, what do you think?

**Comment by glbrntt** [comment]
> The overall intention of the PR makes sense to me; I wonder whether we could find a more elegant way than returning a tuple, though. @glbrntt, what do you think?

Agreed. I'd be fine with something like a `StatusAndMetadata` struct to be honest.

**Comment by glbrntt** [comment]
@fabianfett do you have any plans to pick this work back up?

**Comment by FranzBusch** [comment]
@glbrntt I would also happily pick this up. I was playing around with the implementation of `grpc-status-details-bin` and noticed that returning both `status` and in the `trailingMetadata` in one future makes handling this a lot easier. I am open to suggestions here and happy to contribute :)

**Comment by fabianfett** [comment]
@FranzBusch It’s all yours. 🚀 I sadly don’t have the time right now.

**Comment by glbrntt** [comment]
@FranzBusch you're welcome to pick this up; I started looking at it last week but didn't get much further than this draft. Let me know if you'd like to take this one on.

**Comment by FranzBusch** [comment]
@glbrntt Happy to take this. Would it also be okay to add [this](https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto) proto to the repo and vend it? Or would you leave this to the clients?

**Comment by glbrntt** [comment]
> @glbrntt Happy to take this. 

Awesome, thank you! Let me know if you need anything 😃 

> Would it also be okay to add [this](https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto) proto to the repo and vend it? Or would you leave this to the clients?

I think I'd rather leave this to clients since it wouldn't be directly used by the library.

**Comment by glbrntt** [comment]
hey @FranzBusch -- any updates on this?

**Comment by glbrntt** [comment]
Closing in favour of #873

**Pull request closed without merging**
