### PR TITLE
Rebuild the Carthage project with Swift 5 for gRPC-Core 1.23.

### PR DESCRIPTION
**Pull request by MrMage**
@pacu, @JonasVautherin could you please check whether Carthage still works for you with the project from this branch?

### CODE REVIEW

**Comment by JonasVautherin** [comment]
I don't have my mac for the weekend, I'll test that on Monday and will report back here :+1:.

**Comment by pacu** [comment]
I created a test project that has this Cartfile

```
github "MrMage/grpc-swift" "rebuild-carthage-2"
```

```` bash
carthage update --platform iOS
*** Fetching grpc-swift
*** Checking out grpc-swift at "87e3400754924c556be47887979bc44f218ea6f7"
*** xcodebuild output can be found in /var/folders/zd/zss_3kv112337jq_8hm28j540000gn/T/carthage-xcodebuild.FJAfnw.log
*** Building scheme "SwiftGRPC-Package" in SwiftGRPC-Carthage.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project REDACTED/TestCarthage/Carthage/Checkouts/grpc-swift/SwiftGRPC-Carthage.xcodeproj -scheme SwiftGRPC-Package -configuration Release -derivedDataPath $HOME/Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/grpc-swift/87e3400754924c556be47887979bc44f218ea6f7 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/zd/zss_3kv112337jq_8hm28j540000gn/T/grpc-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/pacu/Repos/ECC/TestCarthage/Carthage/Checkouts/grpc-swift)

````

Log
```
** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwift normal armv7
	Ld /$HOME/Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/grpc-swift/87e3400754924c556be47887979bc44f218ea6f7/Build/Intermediates.noindex/ArchiveIntermediates/SwiftGRPC-Package/IntermediateBuildFilesPath/SwiftGRPC-Carthage.build/Release-iphoneos/CgRPC.build/Objects-normal/armv7/Binary/CgRPC normal armv7
```

**Comment by douglaswsilva** [comment]
Tested it here and got the same problem as @pacu above.

**Comment by MrMage** [comment]
Thanks! It appears that our current method of generating Carthage projects (or fixing the project up to be Carthage-compatible) won't be compatible with Swift 5/Xcode 11. I have updated this PR with the project rebuilt with Swift 4.2, but I am not sure whether we will be able to support Carthage under Xcode 11. There, using SwiftPM directly is probably the way to go.

**Comment by glbrntt** [comment]
> ... using SwiftPM directly is probably the way to go.

Just a note: this has to be via generating the xcodeproj and not via the direct SPM support in Xcode 11 (see: https://github.com/grpc/grpc-swift/issues/478)

**Comment by JonasVautherin** [comment]
> There, using SwiftPM directly is probably the way to go.

Not sure how that will work for iOS projects using Carthage, though :thinking:. On my end, I'm staying with the latest release that was working with Carthage, and hoping it works for as long as possible :see_no_evil:.

If I understand correctly, grpc-swift 1.0 gets rid of CgRPC, so at some point I may as well try to generate an XCode project using [xcodegen](https://github.com/yonaskolb/XcodeGen), and maintain that in a fork. Last time I tried xcodegen, I was stuck because of CgRPC.

**Comment by pacu** [comment]
I'll be probably dropping Carthage support then :(

**Comment by MrMage** [comment]
Dropping Carthage support for what?

**Comment by pacu** [comment]
Have a project for an iOS SDK which has swift-grpc as one of its main dependencies, it will be open source soon, we were aiming to support as many dependency managers as possible but, I guess we will have to put Carthage support on hold for now until we can sort this out.

**Comment by MrMage** [comment]
In general, Carthage causes a lot of work to make SwiftPM projects (especially those with dependencies) play nicely with it. If you have the option _not_ to support it, I would take that option for now until the Carthage situation (maybe) clears up for SwiftGRPC at some point.

**Comment by pacu** [comment]
> In general, Carthage causes a lot of work to make SwiftPM projects (especially those with dependencies) play nicely with it. If you have the option _not_ to support it, I would take that option for now until the Carthage situation (maybe) clears up for SwiftGRPC at some point.

I'll take that advice! I'm sorry I couldn't help much. Swift-GRCP is great :) 
Thank you so much for your time and dedication.

**Pull request merged**
