### PR TITLE
Extract the interface of generated code into protocols for better testability

### PR DESCRIPTION
**Pull request by MrMage**
...and make the implementing classes conform to those protocols. This lets us create custom implementations of those protocols, e.g. mocks/stubs/fakes/spies for testing purposes. In particular, this commit also includes an option to have simple fake implementations generated for the above protocols in addition to the "real" implementations (see #120 for a detailed discussion).

The only breaking change in this code is that the client-side RPC server interface now needs to be instantiated as e.g. `Echo_EchoServiceImpl(address:secure:)` instead of `Echo_EchoService(address:secure:)`. Anywhere else, the protocols have the same name and expose the same interface as the previously-used `final class` implementations, with classes still being used under the hood.

### CODE REVIEW

**Comment by timburks** [comment]
I was unsure of the "generate_mock_code" option name, but it seems to be used by the C++ plugin. Are there any other plugins that use this same option name?

**Comment by MrMage** [comment]
Yeah, I used that option name because I found it for the C++ plugin. It appears that [the Objective-C plugin](https://github.com/grpc/grpc/blob/master/src/compiler/objective_c_plugin.cc) doesn't have an option to generate such mocks. The Go client libraries [can apparently be mocked with Go's `mockgen` tool](https://github.com/grpc/grpc-go/blob/master/Documentation/gomock-example.md). For Java, I guess custom mocks aren't necessary thanks to the presence of great reflection-based mocking frameworks such as Mockito. In theory, one could also use a tool like [Cuckoo](https://github.com/Brightify/Cuckoo) to generate Swift-based mocks _after running the SwiftGRPC codegen_, but I feel that having an option to have the compiler generate primitive mocks without introducing another dependency wouldn't hurt.

I don't care much about the option's name, happy to change it to whatever you propose :-)

**Comment by timburks** [comment]
OK, sorry to nitpick on naming, but here goes...

I'd like to use something more concise than "generate_mock_code", either "mocks" or "stubs", perhaps using [this discussion](https://martinfowler.com/articles/mocksArentStubs.html)) as a guide. On a cursory read, I think that "stubs" is probably the right word, and it matches your usage in the code.

Also the "Impl" suffix doesn't feel very Swifty to me. Could we remove it and instead rename the protocol by adding the "Protocol" suffix? (as in [this style discussion](https://github.com/raywenderlich/swift-style-guide/issues/123#issuecomment-276894689)). Thus  "Echo_EchoSession" and "Echo_EchoSessionStub" would both conform to "Echo_EchoSessionProtocol". This would keep the common case simple.

**Comment by MrMage** [comment]
Have a look at the comment right after that one: https://github.com/raywenderlich/swift-style-guide/issues/123#issuecomment-277068418

I feel that `...Protocol` is redundant — the name itself should describe what this is about, and consumers should only care about the interface exposed by the protocol, not whether they are dealing with a protocol or a class or the concrete implementation or a stub. So library consumers should simply consume the protocols, anyway. (Also, as far as I know, the Swift standard library has moved away from `...Protocol` suffixes.)

Also, this change specifically makes almost `Impl` classes `fileprivate`, so the actual implementation name shouldn't matter, except for the case of `Echo_EchoServiceImpl`. How about renaming that one to e.g. `Echo_EchoServiceClient`, though? Also happy to replace `Impl` in the other cases with something else, if you have a suggestion.

In terms of codegen options, I have renamed the option to `TestStubs` now, and renamed the classes to `...TestStubs` to avoid confusion with gRPC's client-side RPC shims (i.e. the things clients use to call RPC functions on), which are also called stubs by e.g. the C++ implementation. (According to the linked article, these indeed are stubs, not mocks.)

**Comment by MrMage** [comment]
In case this ends up being blocked only by having to replace `...Impl` in the generated `fileprivate` classes (no externally visible symbols are affected), would it be possible to merge this and change the `...Impl` names in a follow-up pull request? I’d like to try moving most of the generated code into a few generic classes in the runtime library instead (to help make reasoning about the generated code easier), but this pull request needs to be merged first and is blocking me from starting work on that.

**Comment by timburks** [comment]
Replacing "Impl" with "Client" works for me. We can make the other Impl changes in a followup PR. When things stabilize, l'll tag and release an 0.4.0 version since there are some breaking API changes already in master.

**Pull request merged**
