### PR TITLE
Add Package.swift for Swift 4.2

### PR DESCRIPTION
**Pull request by keith**
In order to allow dependent packages to build SwiftGRPC with Swift 4.2,
we have to use the new Package.swift format to define
`swiftLanguageVersions` that include the new enum values. In order to
remain backwards compatible with Xcode < 10 and Swift compilers before
4.2 on Linux we have to duplicate the Package.swift file and make one
specifically for 4.2.

### CODE REVIEW

**Comment by keith** [comment]
It's probably worth waiting for a new release with this change https://github.com/kylef/Commander/pull/74 so we can update Commander for 4.2 as well

**Comment by MrMage** [comment]
Sorry, but what are the advantages of building this package with Swift 4.2? Shouldn't the Swift compiler allow mixed builds, i.e. the library consumer is built with 4.2, but SwiftGRPC with 4.1?

**Comment by keith** [comment]
Mix builds do work now, so this update isn't required to build dependent packages right now. I figured this was worth submitting because at some point you're likely going to want to update toolchains and move to this format instead

**Comment by MrMage** [comment]
I think at that point it would make more sense to move the entire library to Swift 4.2. What do you think?

**Comment by MrMage** [comment]
I think for now we don't need any features from Swift 4.2. Once we do, we should be able to drop support for older Swift versions anyway.

@timburks, WDYT?

**Comment by keith** [comment]
Updated the PR to go down the path of requiring the 4.2 toolchain

**Comment by MrMage** [comment]
I think it will be several more months until we want to go Swift 4.2 only. I would suggest closing this PR for now and re-opening when the time comes, to avoid accidentally merging it prematurely.

**Pull request closed without merging**
