### PR TITLE
Updated Dependencies to use latest

### PR DESCRIPTION
**Pull request by mRs-**
This also adds the workaround in https://github.com/grpc/grpc-swift/issues/822

### CODE REVIEW

**Comment by Jake-Prickett** [comment]
I believe this PR will be required for us to release another Pod. With the update to NIOHTTP2, there's a version conflict between dependencies giving a build error for `1.0.0-alpha.13` Podspec validation.

**Comment by mRs-** [comment]
Yeah and the Swift 5.0 Compiler is not happy about the changes... (https://travis-ci.org/github/grpc/grpc-swift/jobs/696149912)

**Comment by Lukasa** [comment]
Huh, that's interesting.

The errors are around the establishment and data transfer report accessing fields in the new NIO Transport Services. Those are guarded behind OS availability guards (`#available` and `@available`), so this ought not to be a problem.

_However_, I think that in this case the CI build is testing 5.0 compiles not by using a recent Xcode in 5.0 mode but by using an _old_ Xcode. In this case, 10.3, which shipped before macOS 10.15. This means it doesn't have the macOS 10.15 SDK and so literally doesn't know these symbols exist. Because availability guards don't affect the parse, just the notion of availability, we error out.

@glbrntt is this testing environment reflective of an intended use case? Are we really saying that we'll support not just "compile in 5.0 mode" but also "compile with the old compiler"?

**Comment by glbrntt** [comment]
> @glbrntt is this testing environment reflective of an intended use case? Are we really saying that we'll support not just "compile in 5.0 mode" but also "compile with the old compiler"?

No, 10.3 was the latest Xcode when we setup the CI, we just haven't changed it yet.

**Comment by Lukasa** [comment]
Cool, we should do that then. :grin:

**Comment by glbrntt** [comment]
hey @mRs-, could you rebase your changes? I've fixed the flaky test and updated the CI.

**Comment by mRs-** [comment]
Yep will do it 👍

**Comment by mRs-** [comment]
The Tests are passing 🎉 All ready to go now

**Comment by glbrntt** [comment]
> I believe this PR will be required for us to release another Pod. With the update to NIOHTTP2, there's a version conflict between dependencies giving a build error for `1.0.0-alpha.13` Podspec validation.

@Jake-Prickett would you mind doing the cocoapods release?

**Comment by glbrntt** [comment]
@Jake-Prickett @MrMage has was updating the pods (CGRPCZlib is done) but is now blocked on NIOSSL which hasn't been updated yet; could you update when you a get a chance?

**Pull request merged**
