### PR TITLE
Add timeout argument to makeCall

### PR DESCRIPTION
**Pull request by KyoheiG3**
Should be able to set a timeout when making a call as written in the comment.
```swift
/// - Parameter timeout: a timeout value in seconds
```
Thanks.

### CODE REVIEW

**Comment by KyoheiG3** [comment]
Thank you for your reply. I have already made it.

**Comment by MrMage** [comment]
Yes, but this is not for use with the generated code, right?

**Comment by KyoheiG3** [comment]
Yes, right.

**Comment by timburks** [comment]
Thanks!

**Pull request merged**
