### PR TITLE
Remove the gRPC Authors copyright header from generated swift files

### LINKED ISSUE #1611: Output shouldn't have gRPC Authors copyright header
Other gPRC generation plugins like the [Official C++ one](https://github.com/grpc/grpc) do not add a copyright header to the generated files that say it is copyright by the "gRPC Authors" like this Swift program does:

https://github.com/grpc/grpc-swift/blob/76d4ec1dff8cfbd5f7363b98a4a9cdb26fb6c6c3/Sources/protoc-gen-grpc-swift/Generator.swift#L110-L135

Although the code requires linking against the Apache-licensed gRPC and Protobuf libraries, as in commonly-used practice of code generators, the output should be owned by the the owner of the input files and the executor of the code generator. Instead it should be up to the author of the `.proto` file to provide their own header through #1610.

### PR DESCRIPTION
**Pull request by kriswuollett**
Motivation:

The common practice of code generators is not to apply their own copyright and license headers to generated files. Instead the output is owned by the owner of the input files and the executor of the code generator.

Fixes #1611.

Modifications:

Removed license header from file generator, test case files, and checks for generated file license headers in the CI sanity license-check.

Results:

End users of protoc-gen-grpc-swift will not have a Copyright by gRPC Authors added to the generated swift files from their own proto files.

Related:

The copyright headers could be added back via #1610.

### CODE REVIEW

**Comment by kriswuollett** [comment]
> [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/1656153/68841963/1612/#/?version=2)
> 
> * [❌](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/1656153/68841963/1612/#/?version=2) - login: @kriswuollett / name: Kristopher Wuollett . The commit ([c74aadb](https://github.com/grpc/grpc-swift/commit/c74aadbf17f785d735f4852303b813df79aa4719)) is not authorized under a signed CLA. [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/1656153/68841963/1612/#/?version=2). For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

In process of setting up organization account for CLA.

**Comment by glbrntt** [comment]
Thanks @kriswuollett -- looks like this was added way back and no one has questioned it since! Please tag me when you get your CLA sorted and I'll take a look.

**Comment by kriswuollett** [comment]
@glbrntt -- Thanks! I'm covered by the CLA now.

**Review by glbrntt — APPROVED** [review]
Thank @kriswuollett -- I don't suppose you're inclined to tackle #1610 as well?

**Comment by kriswuollett** [comment]
> Thank @kriswuollett -- I don't suppose you're inclined to tackle #1610 as well?

I may take a look at it this week. It may be just a matter of copying the logic that already exists in the Swift Protobuf project, more or less.

**Pull request merged**
