### PR TITLE
Add support for `XcodeProjectPlugin`

### PR DESCRIPTION
**Pull request by denil-ct**
Carrying over the changes from https://github.com/apple/swift-protobuf/pull/1408

Can anyone point me on how to test these changes for grpc as I'm not very familiar with grpc.

### CODE REVIEW

**Review by FranzBusch — COMMENTED** [review]
Overall looks good to me. I just realised that we should update the documentation in both repos though. We should add two things:
1. That now the config doesn't need to be at the root of the target anymore since we just search through the sources of a target
2. We should state that how it works for an Xcode project.

**Comment by denil-ct** [comment]
> That now the config doesn't need to be at the root of the target anymore since we just search through the sources of a target

One thing to note here is that the target directory is calculated by deleting the last component of the config. So whatever folder the config resides in would become the target directory, and the file paths mentioned in the config should be relative to that.

**Comment by FranzBusch** [comment]
> One thing to note here is that the target directory is now calculated by deleting the last component of the config. So whatever folder the config resides in would become the target directory, and the file paths mentioned in the config should be relative to that.

That's actually a very important call out! Thanks for stating this. We should clarify this in the Docc docs for the plugins. This is particularly important for the Xcode plugin since there the files can be all over the place.

**Comment by glbrntt** [comment]
@denil-ct could you bring over the changes from protobuf if you get a chance? We'd like to do a release soon and it would be nice to include this change 🙂

**Comment by denil-ct** [comment]
Hey @glbrntt , got a bit busy. Will make the changes by tomorrow.

**Comment by glbrntt** [comment]
No worries, thank you!

**Comment by denil-ct** [comment]
Hey @glbrntt , I'm facing some troubles verifying my changes.

I have this proto file
```proto
syntax = "proto3";

service NoteService {
    rpc Get (NoteRequestId) returns (Note) {}
}

message Note {
    string id = 1;
    string title = 2;
    string content = 3;
}

message NoteRequestId {
    string id = 1;
}
```

But  after the `Note.grpc.swift` file gets generated the message types like `NoteRequestId` and `Note` are not in scope.

The plugin tries to execute this command
```sh
/opt/homebrew/bin/protoc --plugin=protoc-gen-grpc-swift=/${BUILD_DIR}/${CONFIGURATION}/protoc-gen-grpc-swift" --grpc-swift_out=/Users/denilct/Library/Developer/Xcode/DerivedData/ABCApp-gkihnhqrytzfbsbcqflpkdwowxum/SourcePackages/plugins/ABCApp.output/ABCApp/GRPCSwiftPlugin -I /Users/denilct/Documents/ABCApp_2/ABCApp_2 --grpc-swift_opt=Visibility=Public --grpc-swift_opt=Server=false --grpc-swift_opt=Client=true ProtoFiles/Notes/Note.proto
```

**Comment by glbrntt** [comment]
Are you running the protobuf plugin too? The grpc-swift plugin will only generate the service code, it won't generate the `Note` or `NoteRequestId`.

**Comment by denil-ct** [comment]
Ah, I see. Adding the protobuf plugin fixed it. Thanks.

**Comment by denil-ct** [comment]
You can review the changes. @glbrntt

**Review by glbrntt — COMMENTED** [review]
This looks good to me but could you run `./scripts/format.sh` to run the formatter so that CI check passes?

**Comment by denil-ct** [comment]
Have added the changes done by swift-format.

**Review by glbrntt — APPROVED** [review]

**Review by FranzBusch — APPROVED** [review]

**Comment by glbrntt** [comment]
Thanks @denil-ct 🙏

**Pull request merged**
