### PR TITLE
Remove CzLib from dependencies

### PR DESCRIPTION
**Pull request by tikidunpon**
related issue: https://github.com/grpc/grpc-swift/issues/273 and https://github.com/grpc/grpc-swift/issues/272

I removed some CzLib dependencies from sample project. 
It works with an additional header search fixes but it seems like large.
so I divided PR for easy to review.

### CODE REVIEW

**Comment by MrMage** [comment]
BTW, is the related issue #88 or #273 or something else?

**Comment by tikidunpon** [comment]
@MrMage oh.. yes, it is related #273.. I wanna fix „Simple“ on other PR.

**Comment by tikidunpon** [comment]
To running „Echo“ I also fixed some compile error.

**Comment by tikidunpon** [comment]
I will fix Simple too.
> FYI, it looks like the „Simple“ example would need the same changes. I’ll leave it to you if you want to add those as well; otherwise I’ll fix those in a separate PR.

**Pull request merged**
