### PR TITLE
Add note about SPM plugin known issues, provide better errors

### PR DESCRIPTION
**Pull request by glbrntt**

### CODE REVIEW

**Review by FranzBusch — APPROVED** [review]

**Comment by denil-ct** [comment]
@FranzBusch are we not removing `importPaths` option here?

**Comment by FranzBusch** [comment]
> @FranzBusch are we not removing `importPaths` option here?

This is an interesting one. I think we should remove it because I think in the current state it is not useable at all. Though it would be a potentially breaking API. @glbrntt what do you think?

**Comment by glbrntt** [comment]
I don't think we should remove for API reasons. We can detect its presence and emit a warning or something though?

**Comment by FranzBusch** [comment]
Yeah we should probably just warn on this or even error out. The only thing you can pass here right now are absolute paths which would be very brittle anyhow.

**Pull request merged**
