### PR TITLE
Update CocoaPods & Carthage for 0.8.0 release

### PR DESCRIPTION
**Pull request by rebello95**
Updating prior to issuing a new release to include recent commits.

### CODE REVIEW

**Comment by MrMage** [comment]
Closing and re-opening to trigger a fresh CI run...

**Comment by MrMage** [comment]
CI is green now; @rebello95 I'd suggest you merge at your convenience and push the new release to CocoaPods afterwards.

**Comment by MrMage** [comment]
@rebello95 just a quick reminder that you can merge at your convenience :-)

**Comment by rebello95** [comment]
Yep, will do 😄 want to do some tests against master today/tomorrow beforehand

**Comment by MrMage** [comment]
:thumbs-up:

**Comment by rebello95** [comment]
Will also update the Carthage project as part of this PR prior to merging, per https://github.com/grpc/grpc-swift/pull/383

**Comment by MrMage** [comment]
👍 Still LGTM.

**Comment by rebello95** [comment]
Rebased, re-generated carthage project, pushed. Will merge when CI is green

**Pull request merged**
