### PR TITLE
Build carthage-project on Xcode11

### PR DESCRIPTION
**Pull request by pacu**
Motivation:
- Carthage builds fails when using Xcode11 

Modifications: 
- Run ```make project-carthage``` 

All tests passed

### CODE REVIEW

**Comment by MrMage** [comment]
Would this break Carthage builds on Xcode 10?

**Comment by pacu** [comment]
> Would this break Carthage builds on Xcode 10/10.2 (which has Swift 5)?

I'm downloading Xcode 10.3 to test it out on that version. What's the minimum supported version?

**Comment by pacu** [comment]
> Also, did you sign the CLA? The EasyCLA bot is broken right now.

I'm sorry, I missed that part. I'll take my time to read the agreement. I'll comment about me signing the agreement when I do so, If I decide not to do so I'll do it as well but closing the pr afterwards.

**Comment by MrMage** [comment]
> I'm downloading Xcode 10.3 to test it out on that version. What's the minimum supported version?

I guess we could require Xcode 10.2 by now.

**Comment by pacu** [comment]
FWIW I downloaded Xcode 10.2 and installed it's command line tools, then ran ```make project-cartage``` successfully.

# Output

### Xcode Select
```` Bash
pacu$ xcode-select -p
/Applications/Xcode_10_2.app/Contents/Developer
````

### Make clean 
```` Bash
pacu$ make clean
rm -rf Packages
rm -rf .build build
rm -rf SwiftGRPC.xcodeproj
rm -rf Package.pins Package.resolved
rm -rf protoc-gen-swift protoc-gen-swiftgrpc
cd Examples/Google/Datastore && make clean
rm -rf Packages googleapis .build
rm -f Package.pins Datastore Sources/*.pb.swift Sources/*.grpc.swift google.json
rm -rf Package.resolved
cd Examples/Google/NaturalLanguage && make clean
rm -rf Packages googleapis .build
rm -f Package.pins NaturalLanguage Sources/*.pb.swift Sources/*.grpc.swift google.json
rm -rf Package.resolved
cd Examples/Google/Spanner && make clean
rm -rf Packages googleapis .build
rm -f Package.pins Spanner Sources/*.pb.swift Sources/*.grpc.swift google.json
rm -rf Package.resolved
````


### Make project-carthage

```` Bash
pacu$ make project-carthage
swift package generate-xcodeproj --output SwiftGRPC-Carthage.xcodeproj
Fetching https://github.com/apple/swift-protobuf.git
Fetching https://github.com/kylef/Commander.git
Fetching https://github.com/apple/swift-nio-zlib-support.git
Fetching https://github.com/apple/swift-nio-nghttp2-support.git
Fetching https://github.com/apple/swift-nio.git
Fetching https://github.com/apple/swift-nio-http2.git
Fetching https://github.com/kylef/Spectre.git
Completed resolution in 109.29s
Cloning https://github.com/apple/swift-nio-http2.git
Resolving https://github.com/apple/swift-nio-http2.git at 0.2.1
Cloning https://github.com/apple/swift-nio.git
Resolving https://github.com/apple/swift-nio.git at 1.14.1
Cloning https://github.com/apple/swift-nio-nghttp2-support.git
Resolving https://github.com/apple/swift-nio-nghttp2-support.git at 1.0.0
Cloning https://github.com/apple/swift-protobuf.git
Resolving https://github.com/apple/swift-protobuf.git at 1.7.0
Cloning https://github.com/apple/swift-nio-zlib-support.git
Resolving https://github.com/apple/swift-nio-zlib-support.git at 1.0.0
Cloning https://github.com/kylef/Commander.git
Resolving https://github.com/kylef/Commander.git at 0.8.0
Cloning https://github.com/kylef/Spectre.git
Resolving https://github.com/kylef/Spectre.git at 0.9.0
generated: ./SwiftGRPC-Carthage.xcodeproj
````

### Swift test (fails)

 pacu$ swift test
```` bash
Fetching https://github.com/apple/swift-nio-zlib-support.git
Fetching https://github.com/apple/swift-protobuf.git
Fetching https://github.com/apple/swift-nio-nghttp2-support.git
Fetching https://github.com/kylef/Commander.git
Fetching https://github.com/kylef/Spectre.git
Fetching https://github.com/apple/swift-nio-http2.git
Fetching https://github.com/apple/swift-nio.git
Completed resolution in 51.67s
Cloning https://github.com/apple/swift-nio-nghttp2-support.git
Resolving https://github.com/apple/swift-nio-nghttp2-support.git at 1.0.0
Cloning https://github.com/apple/swift-nio.git
Resolving https://github.com/apple/swift-nio.git at 1.14.1
Cloning https://github.com/kylef/Commander.git
Resolving https://github.com/kylef/Commander.git at 0.8.0
Cloning https://github.com/apple/swift-nio-zlib-support.git
Resolving https://github.com/apple/swift-nio-zlib-support.git at 1.0.0
Cloning https://github.com/apple/swift-protobuf.git
Resolving https://github.com/apple/swift-protobuf.git at 1.7.0
Cloning https://github.com/apple/swift-nio-http2.git
Resolving https://github.com/apple/swift-nio-http2.git at 0.2.1
Cloning https://github.com/kylef/Spectre.git
Resolving https://github.com/kylef/Spectre.git at 0.9.0
<unknown>:0: error: failed writing record 'NSColorPicker.h-2HNZ5455T2U7O': failed to rename '/SomePath/grpc-swift/.build/x86_64-apple-macosx/debug/index/store/v5/records/7O/NSColorPicker.h-2HNZ5455T2U7O-temp-5dacf3d0' to '/SomePath/grpc-swift/.build/x86_64-apple-macosx/debug/index/store/v5/records/7O/NSColorPicker.h-2HNZ5455T2U7O': No such file or directory
````

I've deleted derived data and the .build directory and retried, what changed is the name of the file that fails to rename

**Comment by MrMage** [comment]
@pacu, sorry, the question is not whether you can run `make project-carthage` with Xcode 11, but rather whether the Carthage project you generated would be compatible with Xcode 10.2.

**Comment by pacu** [comment]
> @pacu, sorry, the question is not whether you can run `make project-carthage` with Xcode 11, but rather whether the Carthage project you generated would be compatible with Xcode 10.2.

Well, It's difficult to say because now it's not working on either of them :/

**Comment by MrMage** [comment]
Could you check with the project from https://github.com/grpc/grpc-swift/pull/613 instead? If that doesn't work, what is the Carthage error?

**Comment by MrMage** [comment]
Closed in favor of and for reasons outlined in #613.

**Pull request closed without merging**
