### PR TITLE
Add tests to demonstrate security issues

### PR DESCRIPTION
**Pull request by n8armstrong**
There are 2 issues that I am hoping to surface by these tests.

**1. Basic ssl with `roots_pem()` does not appear to be working**
SSL requests using the `roots_pem()` certificate via `ServiceClientBase.init(address:secure:)` where `secure` is `true` results in error. See `EchoTestsRootSecurity` test.

**2. Self-signed ssl certificates do not work** #249 
I have been unable to send requests using a self-signed cert/key pair. See `EchoTestsSelfSigned` test. I included self-signed credentials that I generated using openssl commands.

### CODE REVIEW

**Comment by MrMage** [comment]
In the case of `.root`, you are setting up a non-SSL Server but trying to connect via SSL. That’s not going to work. Also, the case of the default root certs can’t really be tested, because that would require a server cert signed by one of the default root CAs, i.e. a „real“ web server certificate.

**Comment by MrMage** [comment]
Also, which commands exactly did you use to generate the self-signed certs? The existing test certificate is self-signed as well, so in principle self-signed certs should work.

**Comment by MrMage** [comment]
FYI, the tests assume the certificates to be created for the „example.com“ domain; yours need to be created for that domain as well. See the `sslTargetNameOverride` channel argument.

**Comment by n8armstrong** [comment]
@MrMage Thank you for the prompt feedback. What you said about `.root` makes perfect sense to me now. That test can be ignored.

This is how we are generating the self-signed certs:

**Comment by n8armstrong** [comment]
```
openssl req -passin pass:1111 -new -x509 -days 365 -key ca.key -out ca.crt -subj "/CN=${SERVER_CN}"
openssl genrsa -passout pass:1111 -des3 -out server.key 4096
```

**Comment by n8armstrong** [comment]
Self-signing with the correct domain (`example.com`) fixed the issue. Still can't get tls mutual auth to work even with #244 changes but we'll keep that issue separate.

Thanks.

**Pull request closed without merging**
