### PR TITLE
Remove fix-project-settings.rb references from Makefile

### PR DESCRIPTION
**Pull request by glbrntt**
Motivation:

The Makefile referenced a file which no longer exists.

Modifications:

Remove references to that file.

Result:

More happy project generation.

### CODE REVIEW

**Comment by glbrntt** [comment]
Fixes #693

**Comment by glbrntt** [comment]
It was removed with all the other stale documentation/examples etc. 

To be honest, I removed it without thinking. Happy to put it back though if you think?

**Comment by MrMage** [comment]
Hmm. It can help with some people sending wrongly-formatted PRs, for example. Our indentation settings are fairly non-standard.

I would suggest re-adding it.

**Comment by glbrntt** [comment]
Re-added but to `scripts/`

**Pull request merged**
